package com.garpr.android.koin

const val DATABASE_NAME = "GAR_PR_DATABASE"
const val FAVORITE_PLAYERS_KEY_VALUE_STORE = "FAVORITE_PLAYERS_KEY_VALUE_STORE"
const val GAR_PR_API = "GAR_PR_API"
const val GAR_PR_RETROFIT = "GAR_PR_RETROFIT"
const val GENERAL_KEY_VALUE_STORE = "GENERAL_KEY_VALUE_STORE"
const val NOT_GAR_PR_API = "NOT_GAR_PR_API"
const val NOT_GAR_PR_RETROFIT = "NOT_GAR_PR_RETROFIT"
const val PACKAGE_NAME = "PACKAGE_NAME"
const val RANKINGS_POLLING_KEY_VALUE_STORE = "RANKINGS_POLLING_KEY_VALUE_STORE"
const val SMASH_ROSTER_KEY_VALUE_STORE = "SMASH_ROSTER_KEY_VALUE_STORE"
const val SMASH_ROSTER_RETROFIT = "SMASH_ROSTER_RETROFIT"
